//
//  LoginViewController.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 08.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import SnapKit

final class LoginViewController: UIViewController {
    
    private lazy var stackView: UIStackView = {
        let stackView = UIStackView(arrangedSubviews: [emailTextField, passwordTextField, loginButton])
        stackView.axis = .vertical
        stackView.spacing = 24
        stackView.distribution = .equalSpacing
        return stackView
    }()
    
    private var emailTextField = TitleTextField(type: .email)
    private var passwordTextField = TitleTextField(type: .password)
    private lazy var loginButton = AppButton(title: "Войти", action: #selector(loginButtonAction))

    // MARK: - Public properties -

    var presenter: LoginPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        view.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(hideKeyboard)))

        NotificationCenter.default.addObserver(self,
            selector: #selector(keyboardWillShow),
            name: UIResponder.keyboardWillShowNotification,
            object: nil
        )
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.navigationBar.titleTextAttributes = [
            NSAttributedString.Key.foregroundColor: UIColor.appText,
            NSAttributedString.Key.font: UIFont.systemFont(ofSize: 18, weight: .bold)]
    }
    
    @objc
    private func loginButtonAction() {
        hideKeyboard()
    }
    
    @objc
    private func hideKeyboard() {
        view.endEditing(true)
        stackView.snp.remakeConstraints { make in
            make.centerY.equalTo(view)
            make.leading.trailing.equalTo(view).inset(18)
        }
        
        UIView.animate(withDuration: 0.2) {
            self.view.layoutIfNeeded()
        }
    }
    
    @objc 
    private func keyboardWillShow(_ notification: Notification) {
        stackView.snp.remakeConstraints { make in
            make.top.equalTo(view.snp.topMargin).inset(24)
            make.leading.trailing.equalTo(view).inset(18)
        }
        
        UIView.animate(withDuration: 0.2) {
            self.view.layoutIfNeeded()
        }
    }

}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
}

// MARK: - setupView
private extension LoginViewController {
    
    func setupView() {
        title = "Вход"
        view.backgroundColor = .white
        view.addSubview(stackView)
        stackView.snp.makeConstraints { make in
            make.centerY.equalTo(view)
            make.leading.trailing.equalTo(view).inset(18)
        }
    }
}
