//
//  LoginInterfaces.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 08.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol LoginWireframeInterface: WireframeInterface {
    func goToCoffeeShops()
}

protocol LoginViewInterface: ViewInterface {
    func enableMainButton(_ flag: Bool)
    func updateBy(state: LoginPresenter.LoginState)
}

protocol LoginPresenterInterface: PresenterInterface {
    func toggleState()
    
    func emailTextFieldEditingChanged(_ text: String)
    func passwordTextFieldEditingChanged(_ text: String)
    func retryPasswordTextFieldEditingChanged(_ text: String)
    
    func authAction()
}

protocol LoginInteractorInterface: InteractorInterface {
    func requestAuth(type: LoginInteractor.RequsetType, user: UserModel, completion: @escaping (Result<TokenModel, NetworkError>) -> Void)
}
