//
//  LoginViewController.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 08.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import SnapKit

final class LoginViewController: UIViewController {
    
    private lazy var stackView: UIStackView = {
        let stackView = UIStackView(arrangedSubviews: [emailTextField, passwordTextField, mainButton, secondButton])
        stackView.axis = .vertical
        stackView.spacing = 24
        stackView.distribution = .equalSpacing
        return stackView
    }()
    
    private let emailTextField = TitleTextField(type: .email, editingChanged: #selector(emailTextFieldEditingChanged))
    private let passwordTextField = TitleTextField(type: .password, editingChanged: #selector(passwordTextFieldEditingChanged))
    private let retryPasswordTextField = TitleTextField(type: .retryPassword, editingChanged: #selector(retryPasswordTextFieldEditingChanged))
    private lazy var mainButton = AppButton(action: #selector(mainButtonAction))
    
    private lazy var secondButton: UIButton = {
        let button = UIButton(type: .system)
        button.setTitleColor(.appText, for: .normal)
        button.addTarget(self, action: #selector(secondButtonAction), for: .touchUpInside)
        return button
    }()

    // MARK: - Public properties -

    var presenter: LoginPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        
        view.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(hideKeyboard)))

        NotificationCenter.default.addObserver(self,
            selector: #selector(keyboardWillShow),
            name: UIResponder.keyboardWillShowNotification,
            object: nil
        )
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.navigationBar.titleTextAttributes = [
            NSAttributedString.Key.foregroundColor: UIColor.appText,
            NSAttributedString.Key.font: UIFont.systemFont(ofSize: 18, weight: .bold)]
    }
    
    // MARK: - Private
    @objc
    private func secondButtonAction() {
        presenter.toggleState()
    }
    
    @objc
    private func mainButtonAction() {
        hideKeyboard()
        presenter.authAction()
    }
    
    @objc
    private func hideKeyboard() {
        view.endEditing(true)
        stackView.snp.remakeConstraints { make in
            make.centerY.equalTo(view)
            make.leading.trailing.equalTo(view).inset(18)
        }
        
        UIView.animate(withDuration: 0.2) {
            self.view.layoutIfNeeded()
        }
    }
    
    @objc 
    private func keyboardWillShow(_ notification: Notification) {
        stackView.snp.remakeConstraints { make in
            make.top.equalTo(view.snp.topMargin).inset(24)
            make.leading.trailing.equalTo(view).inset(18)
        }
        
        UIView.animate(withDuration: 0.2) {
            self.view.layoutIfNeeded()
        }
    }
    
    @objc
    private func emailTextFieldEditingChanged() {
        presenter.emailTextFieldEditingChanged(emailTextField.text ?? "")
    }
    
    @objc
    private func passwordTextFieldEditingChanged() {
        presenter.passwordTextFieldEditingChanged(passwordTextField.text ?? "")
    }
    
    @objc
    private func retryPasswordTextFieldEditingChanged() {
        presenter.retryPasswordTextFieldEditingChanged(retryPasswordTextField.text ?? "")
    }

}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
    func updateBy(state: LoginPresenter.LoginState) {
        title = state.title
        mainButton.setTitle(state.mainButtonTitle, for: .normal)
        secondButton.setTitle(state.secondButtonTitle, for: .normal)
        retryPasswordTextField.isHidden = state == .login
        
        switch state {
        case .login:
            stackView.removeArrangedSubview(retryPasswordTextField)
        case .register:
            stackView.insertArrangedSubview(retryPasswordTextField, at: 2)
        }
        
        UIView.animate(withDuration: 0.2) {
            self.view.layoutIfNeeded()
        }
    }
    
    func enableMainButton(_ flag: Bool) {
        mainButton.enable(flag)
    }
}

// MARK: - setupView
private extension LoginViewController {
    
    func setupView() {
        view.backgroundColor = .white
        view.addSubview(stackView)
        stackView.snp.makeConstraints { make in
            make.centerY.equalTo(view)
            make.leading.trailing.equalTo(view).inset(18)
        }
    }
}
