//
//  CoffeeShopsInteractor.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 10.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CoffeeShopsInteractor {
}

// MARK: - Extensions -

extension CoffeeShopsInteractor: CoffeeShopsInteractorInterface {
}
