//
//  CoffeeShopsInterfaces.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 10.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CoffeeShopsWireframeInterface: WireframeInterface {
    func openMap()
}

protocol CoffeeShopsViewInterface: ViewInterface {
    func reloadData()
}

protocol CoffeeShopsPresenterInterface: PresenterInterface {
    var numberOfItems: Int { get }
    
    func item(at indexPath: IndexPath) -> String
    func mainButtonAction()
}

protocol CoffeeShopsInteractorInterface: InteractorInterface {
}
