//
//  CoffeeShopsPresenter.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 10.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CoffeeShopsPresenter {
    
    // MARK: - Private properties -
    
    private var items: [String] = ["dfasdf", "fqwfe", "fqwef", "qewfqewf", "wefwregr","dfasdf", "fqwfe", "fqwef", "qewfqewf", "wefwregr","dfasdf", "fqwfe", "fqwef", "qewfqewf", "wefwregr"] {
        didSet {
            view.reloadData()
        }
    }

    private unowned let view: CoffeeShopsViewInterface
    private let interactor: CoffeeShopsInteractorInterface
    private let wireframe: CoffeeShopsWireframeInterface

    // MARK: - Lifecycle -

    init(view: CoffeeShopsViewInterface, interactor: CoffeeShopsInteractorInterface, wireframe: CoffeeShopsWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CoffeeShopsPresenter: CoffeeShopsPresenterInterface {
    var numberOfItems: Int {
        items.count
    }
    
    func item(at indexPath: IndexPath) -> String {
        items[indexPath.row]
    }
    
    func mainButtonAction() {
        wireframe.openMap()
    }
}
