//
//  CoffeeShopsViewController.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 10.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CoffeeShopsViewController: UIViewController {
    
    private lazy var tableView: UITableView = {
        let tableView = UITableView()
        tableView.register(CoffeeTableViewCell.self, forCellReuseIdentifier: "CoffeeTableViewCell")
        tableView.dataSource = self
        tableView.delegate = self
        tableView.separatorStyle = .none
        tableView.contentInset = .init(top: 15, left: 0, bottom: 0, right: 0)
        return tableView
    }()
    
    private lazy var mainButton = AppButton(action: #selector(mainButtonAction))

    // MARK: - Public properties -

    var presenter: CoffeeShopsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Ближайшие кофейни"
        setupView()
        presenter.getCoffe()
    }
    
    // MARK: - Private

    @objc
    private func mainButtonAction() {
        presenter.mainButtonAction()
    }
}

// MARK: - Extensions -

extension CoffeeShopsViewController: CoffeeShopsViewInterface {
    func reloadData() {
        tableView.reloadData()
    }
}

// MARK: - setupView
private extension CoffeeShopsViewController {
    
    func setupView() {
        view.backgroundColor = .white
        mainButton.setTitle("На карте", for: .normal)
        mainButton.enable(true)
        view.addSubview(tableView)
        view.addSubview(mainButton)
        tableView.snp.makeConstraints { make in
            make.top.leading.trailing.equalTo(view)
        }
        mainButton.snp.makeConstraints { make in
            make.leading.trailing.equalTo(view).offset(18).inset(18)
            make.top.equalTo(tableView.snp.bottom).offset(18)
            make.bottom.equalTo(view.snp.bottomMargin).offset(20)
        }
    }
}

// MARK: - UITableViewDataSource
extension CoffeeShopsViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        presenter.numberOfItems
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "CoffeeTableViewCell", for: indexPath)
        
        guard let cell = cell as? CoffeeTableViewCell else { return cell }
        let item = presenter.item(at: indexPath)
        cell.configure(mainText: item.name, secondText: "\(item.id)")
        
        return cell
    }
}

// MARK: - UITableViewDelegate
extension CoffeeShopsViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
    
}
