//
//  CoffeeShopsInterfaces.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 10.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CoffeeShopsWireframeInterface: WireframeInterface {
    func openMap()
}

protocol CoffeeShopsViewInterface: ViewInterface {
    func reloadData()
}

protocol CoffeeShopsPresenterInterface: PresenterInterface {
    var numberOfItems: Int { get }

    func getCoffe()
    func item(at indexPath: IndexPath) -> CoffeeShopModel
    func mainButtonAction()
}

protocol CoffeeShopsInteractorInterface: InteractorInterface {
    func requestCoffe(completion: @escaping (Result<CoffeeShopModels, NetworkError>) -> Void)
}
