//
//  CoffeeShopsWireframe.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 10.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CoffeeShopsWireframe: BaseWireframe<CoffeeShopsViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = CoffeeShopsViewController()
        super.init(viewController: moduleViewController)

        let interactor = CoffeeShopsInteractor()
        let presenter = CoffeeShopsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CoffeeShopsWireframe: CoffeeShopsWireframeInterface {
    func openMap() {
        navigationController?.pushViewController(MapViewController(), animated: true)
    }
}
