//
//  CoffeeShopsViewController.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 10.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CoffeeShopsViewController: UIViewController {
    
    private lazy var tableView: UITableView = {
        let tableView = UITableView()
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cell")
        tableView.dataSource = self
        tableView.delegate = self
        tableView.selectionFollowsFocus = false
        tableView.separatorStyle = .none
        return tableView
    }()
    
    private lazy var mainButton = AppButton(action: #selector(mainButtonAction))

    // MARK: - Public properties -

    var presenter: CoffeeShopsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Ближайшие кофейни"
        setupView()
        presenter.getCoffe()
    }
    
    // MARK: - Private

    @objc
    private func mainButtonAction() {
        presenter.mainButtonAction()
    }
}

// MARK: - Extensions -

extension CoffeeShopsViewController: CoffeeShopsViewInterface {
    func reloadData() {
        tableView.reloadData()
    }
}

// MARK: - setupView
private extension CoffeeShopsViewController {
    
    func setupView() {
        view.backgroundColor = .white
        mainButton.setTitle("На карте", for: .normal)
        view.addSubview(tableView)
        view.addSubview(mainButton)
        tableView.snp.makeConstraints { make in
            make.top.leading.trailing.equalTo(view)
        }
        mainButton.snp.makeConstraints { make in
            make.leading.trailing.bottom.equalTo(view).offset(18).inset(18)
            make.top.equalTo(tableView.snp.bottom).offset(18)
        }
    }
}

// MARK: - UITableViewDataSource
extension CoffeeShopsViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        presenter.numberOfItems
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        
        let backgroundView = UIView()
        backgroundView.backgroundColor = UIColor.appButtonText
        cell.backgroundView = backgroundView
        
        var configuration = UIListContentConfiguration.subtitleCell()
        configuration.secondaryTextProperties.color = .appPlaceholderText
        configuration.textProperties.color = .appText
        
        let item = presenter.item(at: indexPath)
        
        configuration.text = item.name
        configuration.secondaryText = "\(item.id)"
        cell.contentConfiguration = configuration
        
        return cell
    }
}

// MARK: - UITableViewDelegate
extension CoffeeShopsViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
    
}
