//
//  MenuInteractor.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 11.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MenuInteractor {
    
    var id: Int
    
    init(id: Int) {
        self.id = id
    }
}

// MARK: - Extensions -

extension MenuInteractor: MenuInteractorInterface {
    func getMenu(completion: @escaping (Result<CoffeeModels, NetworkError>) -> Void) {
        Network.sendRequest(route: .menu(id: id), decodeTo: CoffeeModels.self) { response, error in
            if let error = error {
                completion(.failure(error))
                return
            }
            
            if let response = response {
                completion(.success(response))
                return
            }
        }
    }
}
