//
//  MenuInterfaces.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 11.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MenuWireframeInterface: WireframeInterface {
}

protocol MenuViewInterface: ViewInterface {
    func reloadData()
}

protocol MenuPresenterInterface: PresenterInterface {
    var numberOfItems: Int { get }

    func item(at indexPath: IndexPath) -> CoffeeModel
    func didSelectItem(at indexPath: IndexPath)
}

protocol MenuInteractorInterface: InteractorInterface {
    func getMenu(completion: @escaping (Result<CoffeeModels, NetworkError>) -> Void)
}
