//
//  MenuWireframe.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 11.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MenuWireframe: BaseWireframe<MenuViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(id: Int) {
        let moduleViewController = MenuViewController()
        super.init(viewController: moduleViewController)

        let interactor = MenuInteractor(id: id)
        let presenter = MenuPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MenuWireframe: MenuWireframeInterface {
    func openOrder() {
        navigationController?.pushWireframe(OrderWireframe())
    }
}
