//
//  MenuInterfaces.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 11.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MenuWireframeInterface: WireframeInterface {
}

protocol MenuViewInterface: ViewInterface {
}

protocol MenuPresenterInterface: PresenterInterface {
}

protocol MenuInteractorInterface: InteractorInterface {
    func getMenu(completion: @escaping (Result<CoffeeModels, NetworkError>) -> Void)
}
