//
//  MenuViewController.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 11.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MenuViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: MenuPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension MenuViewController: MenuViewInterface {
}

// MARK: - setupView
private extension MenuViewController {
    
    func setupView() {
        view.backgroundColor = .white
    }
}
