//
//  OrderViewController.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 18.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OrderViewController: UIViewController {
    
    private lazy var tableView: UITableView = {
        let tableView = UITableView()
        tableView.register(CoffeeTableViewCell.self, forCellReuseIdentifier: "OrderTableViewCell")
        tableView.dataSource = self
        tableView.delegate = self
        tableView.separatorStyle = .none
        tableView.contentInset = .init(top: 15, left: 0, bottom: 0, right: 0)
        return tableView
    }()
    
    private lazy var mainButton = AppButton(action: #selector(mainButtonAction))

    // MARK: - Public properties -

    var presenter: OrderPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Ваш заказ"
        navigationItem.backButtonTitle = ""
        setupView()
    }

    // MARK: - Private

    @objc
    private func mainButtonAction() {
        presenter.mainButtonAction()
    }
}

// MARK: - Extensions -

extension OrderViewController: OrderViewInterface {
    func reloadData() {
        tableView.reloadData()
    }
}

// MARK: - setupView
private extension OrderViewController {
    
    func setupView() {
        view.backgroundColor = .white
        mainButton.setTitle("Оплатить", for: .normal)
        mainButton.enable(true)
        view.addSubview(tableView)
        view.addSubview(mainButton)
        tableView.snp.makeConstraints { make in
            make.top.leading.trailing.equalTo(view)
        }
        mainButton.snp.makeConstraints { make in
            make.leading.trailing.equalTo(view).offset(18).inset(18)
            make.top.equalTo(tableView.snp.bottom).offset(18)
            make.bottom.equalTo(view.snp.bottomMargin).offset(20)
        }
    }
}

// MARK: - UITableViewDataSource
extension OrderViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        presenter.numberOfItems
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "OrderTableViewCell", for: indexPath)
        
        guard let cell = cell as? CoffeeTableViewCell else { return cell }
        let item = presenter.item(at: indexPath)
        cell.configure(type: .order, mainText: item.coffee.name, secondText: "\(item.coffee.price * item.count)")
        
        return cell
    }
}

// MARK: - UITableViewDelegate
extension OrderViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
//        presenter.didSelectItem(at: indexPath)
        tableView.deselectRow(at: indexPath, animated: true)
    }
    
}
