//
//  OrderInteractor.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 18.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OrderInteractor {
}

// MARK: - Extensions -

extension OrderInteractor: OrderInteractorInterface {
}
