//
//  OrderPresenter.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 18.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OrderPresenter {
    
    // MARK: - Private properties -

    private unowned let view: OrderViewInterface
    private let interactor: OrderInteractorInterface
    private let wireframe: OrderWireframeInterface
    private var orders: OrderModels = []

    // MARK: - Lifecycle -

    init(view: OrderViewInterface, interactor: OrderInteractorInterface, wireframe: OrderWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension OrderPresenter: OrderPresenterInterface {
    var numberOfItems: Int {
        orders.count
    }
    
    func item(at indexPath: IndexPath) -> OrderModel {
        orders[indexPath.row]
    }
    
    func mainButtonAction() {
        print("#debug order action = \(orders)")
    }
    
}
