//
//  OrderInterfaces.swift
//  CashkaChoffe
//
//  Created by Vlad Ralovich on 18.02.2024.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol OrderWireframeInterface: WireframeInterface {
}

protocol OrderViewInterface: ViewInterface {
    func reloadData()
}

protocol OrderPresenterInterface: PresenterInterface {
    var numberOfItems: Int { get }

    func item(at indexPath: IndexPath) -> OrderModel
    func mainButtonAction()
}

protocol OrderInteractorInterface: InteractorInterface {
}
